<?php

namespace Safronik\Layout\Settings\Types;

use Safronik\Layout\Settings\Element;

class Tab  extends Element{
	
	public $active = false;
	
	/**
	 * @param $element_properties
	 */
	public function __construct( $element_properties )
	{
		parent::__construct( $element_properties );
	}
	
	protected function drawElement()
	{
	
	}
	
	protected function appendCSSClasses()
	{
		parent::appendCSSClasses(); // TODO: Change the autogenerated stub
		if( $this->active ){
			$this->classes[] = $this->block . '--active';
		}
	}

}