<?php

namespace Safronik\Layout\Settings\Types;

class TabHeading extends \Safronik\Layout\Settings\Element{
	
	public $active = false;
	
	/**
	 * @param $element_properties
	 */
	public function __construct( $element_properties )
	{
		parent::__construct( $element_properties );
	}
	
	protected function drawElement()
	{
		echo "<span class='{$this->block}-title'>$this->title</span>";
	}
	
	protected function appendCSSClasses()
	{
		parent::appendCSSClasses(); // TODO: Change the autogenerated stub
		if( $this->active ){
			$this->classes[] = $this->block . '--active';
		}
	}
}